In [1]:

import tensorflow as tf

## Tensor

A tensor is a generalisation of vectors and matrices to an arbitrary number of dimensions. Intuitively, a tensor represents a collection of numbers arranged in a particular shape.

In [2]:
# 0D tensor
d0 = tf.ones((1,))

# 1D tensor
d1 = tf.ones((2,))

# 2D tensor
d2 = tf.ones((2,2))

# 3D tensor
d3 = tf.ones((2, 2, 2))

In [3]:
type(d0)

tensorflow.python.framework.ops.EagerTensor

In [11]:

# to print tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


## Constants

A constant is the simplest type of tensor we can create. It is immutable and cannot be trained. However, it can take on any dimension.

In [5]:

# 3x2 constant of 3s
a = tf.constant(3, shape=[3,2])
print(a.numpy())

[[3 3]
 [3 3]
 [3 3]]


In [6]:

# 2x2 constant of [1,2,3,4]
b = tf.constant([1,2,3,4], shape=[2,2])
print(b.numpy())

[[1 2]
 [3 4]]


## Variables

Unlike a constant, the value of a variable is mutable. It can also be shared and persisted. However, its data type and shape are fixed.

In [7]:

# Declare variable with fixed data type. Shape is also fixed.
a0 = tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
print(a0.numpy())

[1. 2. 3. 4. 5. 6.]


In [8]:

# Try to change a variable's shape 
try:
    a1 = tf.Variable([1,2,3,4,5,6], shape=[3,2])
except ValueError:
    print("ValueError: Cannot change a variable's shape.")
else:
    print(a1.numpy())

ValueError: Cannot change a variable's shape.


In [10]:

# Compute the product of a variable vs a constant
c = tf.constant(2, tf.float32)

prod0 = tf.multiply(a0, c)
print("prod0:", prod0)

prod1 = a0 * c
print("prod1:", prod1)

prod0: tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)
prod1: tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)
