In [1]:

import tensorflow as tf

In [2]:
# 0D tensors
A0 = tf.constant([1])
B0 = tf.constant([2])

# 1D tensors
A1 = tf.constant([1,2])
B1 = tf.constant([3,4])

# 2D tensors
A2 = tf.constant([[[1,2], [3,4]]])
B2 = tf.constant([[5,6], [7,8]])

## add() operator

The add() operation performs element-wise addition with two tensors. Element-wise addition mandates that both tensors have the same shape.

In [3]:
C0 = tf.add(A0, B0)
print("C0:", C0)

C1 = tf.add(A1, B1)
print("C1:", C1)

C2 = tf.add(A2, B2)
print("C2:", C2)

C0: tf.Tensor([3], shape=(1,), dtype=int32)
C1: tf.Tensor([4 6], shape=(2,), dtype=int32)
C2: tf.Tensor(
[[[ 6  8]
  [10 12]]], shape=(1, 2, 2), dtype=int32)


## multiply() operator

The multiply() operator performs element-wise multiplication with two tensors. The tensors must have the same shape.

In [4]:
D0 = tf.multiply(A0, B0)
print("D0:", D0)

D1 = tf.multiply(A1, B1)
print("D1:", D1)

D2 = tf.multiply(A2, B2)
print("D2:", D2)

D0: tf.Tensor([2], shape=(1,), dtype=int32)
D1: tf.Tensor([3 8], shape=(2,), dtype=int32)
D2: tf.Tensor(
[[[ 5 12]
  [21 32]]], shape=(1, 2, 2), dtype=int32)


## matmul() operator

The matmul() operator performs matrix multiplication with two tensors. The number of rows in one tensor should be the same as the number of columns in the other tensor, and the tensors must be at least 2D.

In [5]:
E2 = tf.matmul(A2, B2)
print("E2:", E2)

E2: tf.Tensor(
[[[19 22]
  [43 50]]], shape=(1, 2, 2), dtype=int32)


## reduce_sum() operator

The reduce_sum() operator performs summation over specified dimensions of a tensor.

In [6]:

# define 2x3x4 tensor of ones for reduce_sum() example
A = tf.ones([2,3,4])
print(A.numpy())

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:

S = tf.reduce_sum(A)
print("S:", S)

S1 = tf.reduce_sum(A, 0) # sum over dimension 0 (rows)
print("S1:", S1)

S2 = tf.reduce_sum(A, 1) # sum over dimension 1 (columns)
print("S2:", S2)

S3 = tf.reduce_sum(A, 2) # sum over dimension 2 (tensors)
print("S3:", S3)

S: tf.Tensor(24.0, shape=(), dtype=float32)
S1: tf.Tensor(
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]], shape=(3, 4), dtype=float32)
S2: tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(2, 4), dtype=float32)
S3: tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)
